config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  devise_for :admins

  namespace :admin do
    root "pages#index"
    resources :admins, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products

    resources :orders do
      resources :order_rows, as: "row"
    end
  end

  resources :products, only: [:index, :show]
  resource :cart, only: [:show, :update, :destroy]
  resource :order, only: [:new, :create]
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_rows, autosave: true,
                        dependent: :destroy

  belongs_to :billing_address, class_name: "Address",
                               dependent: :destroy,
                               autosave: true

  belongs_to :shipping_address, class_name: "Address",
                                dependent: :destroy,
                                autosave: true
end

app/controllers/admin/orders_controller.rb
require "order_status_policy"

class Admin::OrdersController < Admin::BaseController
  def index
    @orders = Order.all.paginate(page: params[:page], per_page: 50)
  end

  def show
    @order = Order.includes(order_rows: [:product]).find(params[:id])
  end

  def edit
    @order = Order.includes(order_rows: [:product]).find(params[:id])
  end

  def update
    @order = Order.includes(:billing_address,
                            :shipping_address,
                            :order_rows).find(params[:id])

    params[:sent] ? mark_as_sent : update_order
    check_for_completion
  end

  def destroy
    Order.find(params.require(:id)).destroy
    redirect_to admin_orders_path
  end

  private

  def address_params(type)
    params.require(:order)
          .require(type)
          .permit(:firstname, :lastname, :street, :postal_code, :city)
  end

  def check_for_completion
    OrderStatusPolicy.complete? @order
    flash.now[:success] = t ".success" if @order.save
  rescue OrderStatusPolicy::NotCompleteError
    flash.now[:error] = t ".order_not_complete"
  end

  def mark_as_sent
    @order.order_rows.each { |r| r.sent = true }
    @order.status = 4
  end

  def update_order
    @order.assign_attributes(params.require(:order).permit(:status))
    @order.billing_address.assign_attributes(address_params(:billing_address))
    @order.shipping_address.assign_attributes(address_params(:shipping_address))
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    redirect_to cart_path, notice: t(".failure") if @items_in_cart < 1
    @order = Order.new
    @order.billing_address = Address.new
    @order.shipping_address = Address.new
  end

  def create
    billing = Address.new(address_params(:billing_address))
    shipping = Address.new(address_params(:shipping_address))

    @order = OrderService.checkout(billing: billing,
                                   cart: CartService,
                                   shipping: shipping)
    if @order.save
      CartService.destroy
      flash[:success] = t ".success"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def address_params(type)
    params.require(:order)
          .require(type)
          .permit(:firstname,
                  :lastname,
                  :street,
                  :city,
                  :postal_code)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def order_statuses
    %w(new paused ready sent finished)
  end

  def number_of_statuses
    order_statuses.zip(0..order_statuses.count)
  end

  def status_for(n)
    order_statuses[n]
  end
end

app/views/admin/orders/_form.html.slim
.col-xs-12
  = form_for [:admin, @order], remote: true do |f|
    -if @order.errors.any?
      #error_explanation.col-xs-12.alert.alert-danger
        h2 = pluralize(@order.errors.count, "error")
          | prohibited this user from being saved:
        ul
        - @order.errors.full_messages.each do |msg|
          li = msg

    .col-xs-12
      h3 Order details
      .form-group
        = f.label :status
        = f.select :status, number_of_statuses, {},  class: "form-control"

    = f.fields_for :billing_address, @order.billing_address do |billing|
      .col-xs-12
        h3 Billing address
        = render "form_address", a: billing

    = f.fields_for :shipping_address, @order.shipping_address do |shipping|
      .col-xs-12
        h3 Shipping address
        = render "form_address", a: shipping

    .col-xs-12.text-right
        = f.submit "Update", class: "btn btn-success"

app/views/admin/orders/_form_address.html.slim
.form-group.col-xs-6
  = a.label :firstname
  = a.text_field :firstname, class: "form-control"
.form-group.col-xs-6
  = a.label :lastname
  = a.text_field :lastname, class: "form-control"
.form-group.col-xs12
  = a.label :street
  = a.text_field :street, class: "form-control"
.form-group.col-xs-12
  = a.label :postal_code
  = a.text_field :postal_code, class: "form-control"
.form-group.col-xs-12
  = a.label :city
  = a.text_field :city, class: "form-control"

app/views/admin/orders/_order_table_product.html.slim
table.table.table-striped
  tr
    th Id
    th Name
    th Quantity
    th
    th Price per item
    th total
    th Status
    th

  - if @order.order_rows.empty?
    tr
      td.text-center colspan="8" No items added
  - else
    - @order.order_rows.each.each do |row|
      tr id="admin-order-product-row-#{row.id}"
        = render "admin/order_rows/row", row: row

app/views/admin/orders/_show_order_address.html.slim
.row
  .col-xs-12.col-sm-6
    h2 Billing address
    p = @order.billing_address.fullname
    p = @order.billing_address.street
    p = @order.billing_address.postal_code
    p = @order.billing_address.city


  .col-xs-12.col-sm-6
    h2 Shipping address
    p = @order.shipping_address.fullname
    p = @order.shipping_address.street
    p = @order.shipping_address.postal_code
    p = @order.shipping_address.city

app/views/admin/orders/edit.html.slim
#edit-order-form.col-xs-12
  = render "form"

app/views/admin/orders/index.html.slim
.col-xs-12
  h1 Orders
.col-xs-12
table.table.table-striped
  tr
    th id
    th status
    th created
    th last changed
    th
  - unless @orders.present?
    tr
      td.text-center colspan = "5"
        |No orders have been places

  - @orders.each.each do |o|
    tr
      td = o.id
      td = status_for o.status
      td = o.created_at
      td = o.updated_at
      td
        = link_to "View", admin_order_path(o),
                          class: "btn btn-default"
        - unless o.status == 4
          = link_to "Sent", admin_order_path(o, sent: true),
                            method: :patch,
                            remote: true,
                            class: "btn btn-success"

app/views/admin/orders/show.html.slim
.row
  .col-xs-12
    h1 Order #{@order.id}

.row.order-info
  .col-xs-3
    p Created at:
    = @order.created_at

  .col-xs-3
    p Last changed:
    = @order.updated_at

  .col-xs-3
    p Status:
    = status_for @order.status

.row
  = render "show_order_address"

.row
  .col-xs-12.text-right
    = link_to "Edit", edit_admin_order_path(@order),
                        class: "btn btn-default"
    = link_to "Remove", admin_order_path(@order),
                        method: :delete,
                        class: "btn btn-danger",
                        data: { confirm: "Are your sure you want to remove the order?" }

.row
  .col-xs-12
    h2 Products

.row
  .col-xs-12
    = render "order_table_product"