config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  devise_for :admins

  namespace :admin do
    root "pages#index"
    resources :admins, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products

    resources :orders do
      resources :order_rows, as: "row"
    end
  end

  resources :products, only: [:index, :show]
  resource :cart, only: [:show, :update, :destroy]
  resource :order, only: [:new, :create]
end

app/views/admin/admins/_form.html.slim
= form_for [:admin, @admin] do |f|
  -if @admin.errors.any?
    #error_explanation.col-xs-12.alert.alert-danger
      h2 = pluralize(@admin.errors.count, "error")
        | prohibited this user from being saved:
      ul
      - @admin.errors.full_messages.each do |msg|
        li = msg

  .form-group
    = f.label :email
    = f.text_field :email, class: "form-control", type: :email

  .form-group
    = f.label :password
    = f.text_field :password, class: "form-control", type: :password

  .form-group
    = f.label :password_confirmation
    = f.text_field :password_confirmation, class: "form-control", type: :password

  = f.submit "Save", class: "btn btn-primary"
  - if @admin.id.present?
    = link_to "Remove",
              admin_admin_path(@admin),
              method: :delete,
              class: "btn btn-danger"

app/views/admin/admins/edit.html.slim
= render "form"

app/views/admin/admins/index.html.slim
h1 Administrators

= link_to "Add admin", new_admin_admin_path, class: "btn btn-default"

table.table.table-striped
  tr
    th Id
    th Email
    th Created
    th
  - @admins.each do |a|
    tr
      td = a.id
      td = a.email
      td = a.created_at
      td
        = link_to "Edit",
                  edit_admin_admin_path(a),
                  class: "btn btn-default"
        = link_to "Remove", admin_admin_path(a),
                            method: :delete,
                            class: "btn btn-danger",
                            data: { confirm: "Are you sure?" }

.col-xs-12.text-center
  = will_paginate @admins, renderer: BootstrapPagination::Rails

app/views/admin/admins/new.html.slim
.col-xs-12
  h1 Edit
  = render "form"