config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  devise_for :admins

  namespace :admin do
    root "pages#index"
    resources :admins, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products

    resources :orders do
      resources :order_rows, as: "row"
    end
  end

  resources :products, only: [:index, :show]
  resource :cart, only: [:show, :update, :destroy]
  resource :order, only: [:new, :create]
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Paperclip::Glue

  scope :by_id,     -> { order(id: :asc) }
  scope :availible, -> { by_id.where("quantity > 0") }

  has_attached_file :picture,
                    styles: { thumb: "400x250>" },
                    default_url: ":style/missing.png"
  validates_attachment_content_type :picture,
                                    content_type: %r{/\Aimage\/.*\Z/},
                                    if: -> { picture.content_type.blank? }

  validates :description, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true

  def increase_quantity(n)
    self.quantity += n
    save
  end

  def decrease_quantity(n)
    self.quantity -= n
    save
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :assign_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.by_id.paginate(page: params[:page], per_page: 50)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_product_path(@product)
      flash[:success] = t ".success"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:success] = t ".success"
      redirect_to admin_product_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t(".success")
      redirect_to admin_products_path
    else
      flash[:notice] = t(".failed")
      redirect_to admin_product_path(@product)
    end
  end

  private

  def assign_product
    @product = Product.find(params.require(:id))
  end

  def product_params
    params.require(:product).permit(:name,
                                    :price,
                                    :quantity,
                                    :description,
                                    :picture)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.availible
                       .paginate(page: params[:page], per_page: 9)
  end

  def show
    @product = Product.find(params.require(:id))
  end
end

app/views/admin/products/_form.html.slim
= form_for [:admin, @product] do |f|
  -if @product.errors.any?
    #error_explanation.col-xs-12.alert.alert-danger
      h2 = pluralize(@product.errors.count, "error")
        | prohibited this user from being saved:
      ul
      - @product.errors.full_messages.each do |msg|
        li = msg

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .row
    .form-group.col-sm-6
      = f.label :price
      = f.text_field :price, class: "form-control", type: :number

    .form-group.col-sm-6
      = f.label :quantity
      = f.text_field :quantity, class: "form-control", type: :number

  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"

  .form-group
    = f.file_field :picture


  = f.submit "Save", class: "btn btn-primary"
  - if @product.id.present?
    = link_to "Remove",
              admin_product_path(@product),
              method: :delete,
              class: "btn btn-danger",
              data: { confirm: "Are you sure?" }

app/views/admin/products/index.html.slim
h1 Products

= link_to "Add product", new_admin_product_path, class: "btn btn-default"

table.table.table-striped
  tr
    th Id
    th Name
    th Price
    th quantity
    th
  - unless @products.present?
    tr
      td.text-center colspan = "5"
        |No products have been added

  - @products.each do |p|
    tr
      td = p.id
      td = link_to p.name, admin_product_path(p)
      td = p.price
      td = p.quantity
      td
        = link_to "Edit", edit_admin_product_path(p),
                          class: "btn btn-default"
        = link_to "Remove", admin_product_path(p),
                            method: :delete,
                            class: "btn btn-danger",
                            data: { confirm: "Are you sure?" }

.col-xs-12.text-center
  = will_paginate @products, renderer: BootstrapPagination::Rails

app/views/admin/products/new.html.slim
= render "form"

app/views/admin/products/show.html.slim
.row
  = image_tag @product.picture

h3 Name:
= @product.name

h3 Price:
= @product.price

h3 Quantity:
= @product.quantity

h3 Description:
= @product.description

- if @product.present?
  div
    = link_to "Edit", edit_admin_product_path(@product), class: "btn btn-default"
    = link_to "Remove", admin_product_path(@product),
                        method: :delete,
                        class: "btn btn-danger",
                        data: { confim: "Are you sure?" }