config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  devise_for :admins

  namespace :admin do
    root "pages#index"
    resources :admins, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products

    resources :orders do
      resources :order_rows, as: "row"
    end
  end

  resources :products, only: [:index, :show]
  resource :cart, only: [:show, :update, :destroy]
  resource :order, only: [:new, :create]
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Paperclip::Glue

  scope :by_id,     -> { order(id: :asc) }
  scope :availible, -> { by_id.where("quantity > 0") }

  has_attached_file :picture,
                    styles: { thumb: "400x250>" },
                    default_url: ":style/missing.png"
  validates_attachment_content_type :picture,
                                    content_type: %r{/\Aimage\/.*\Z/},
                                    if: -> { picture.content_type.blank? }

  validates :description, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true

  def increase_quantity(n)
    self.quantity += n
    save
  end

  def decrease_quantity(n)
    self.quantity -= n
    save
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :assign_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.by_id.paginate(page: params[:page], per_page: 50)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_product_path(@product)
      flash[:success] = t ".success"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:success] = t ".success"
      redirect_to admin_product_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t(".success")
      redirect_to admin_products_path
    else
      flash[:notice] = t(".failed")
      redirect_to admin_product_path(@product)
    end
  end

  private

  def assign_product
    @product = Product.find(params.require(:id))
  end

  def product_params
    params.require(:product).permit(:name,
                                    :price,
                                    :quantity,
                                    :description,
                                    :picture)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.availible
                       .paginate(page: params[:page], per_page: 9)
  end

  def show
    @product = Product.find(params.require(:id))
  end
end

app/views/products/index.html.slim
.col-xs-12.text-center
  h1 E-commerce
  - @products.each do |p|
    .col-sm-4.product.well
      = link_to image_tag(p.picture(:thumb), class: "img-responsive"), product_path(p)
      h2 = p.name
      = p.price
      |  kr
.col-xs-12.text-center
  = will_paginate @products, renderer: BootstrapPagination::Rails

app/views/products/show.html.slim
.row
  .col-xs-12.col-sm-8
    = image_tag @product.picture, class: "img-responsive center-block"

  .col-xs-12.col-sm-4
    h3 Name:
    = @product.name

    h3 Price:
    = @product.price

    h3 Quantity:
    = @product.quantity

    h3 Description:
    = @product.description

    br
    br
    = form_tag cart_path(id: @product), method: :patch, remote: :true
      = submit_tag "Add to cart", class: "btn btn-success"